sudo: false

language: node_js
node_js:
  - 6

before_install:
  - npm install -g npx
  - npm install nwb codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
